const valorantAgents = [
  {
    name: "Jett",
    class: "Duelist",
    smoke: true,
    flash: false,
    heal: false,
    molly: false,
    stun: false,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Phoenix",
    class: "Duelist",
    smoke: true,
    flash: true,
    heal: true,
    molly: true,
    stun: false,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Sage",
    class: "Sentinel",
    smoke: false,
    flash: false,
    heal: true,
    molly: false,
    stun: false,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Sova",
    class: "Initiator",
    smoke: false,
    flash: false,
    heal: false,
    molly: false,
    stun: false,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Cypher",
    class: "Sentinel",
    smoke: true,
    flash: false,
    heal: false,
    molly: false,
    stun: true,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Viper",
    class: "Controller",
    smoke: true,
    flash: false,
    heal: false,
    molly: true,
    stun: false,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Brimstone",
    class: "Controller",
    smoke: true,
    flash: false,
    heal: false,
    molly: true,
    stun: false,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Raze",
    class: "Duelist",
    smoke: false,
    flash: false,
    heal: false,
    molly: false,
    stun: false,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Omen",
    class: "Controller",
    smoke: true,
    flash: true,
    heal: false,
    molly: false,
    stun: false,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Reyna",
    class: "Duelist",
    smoke: false,
    flash: true,
    heal: true,
    molly: false,
    stun: false,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Killjoy",
    class: "Sentinel",
    smoke: false,
    flash: false,
    heal: false,
    molly: false,
    stun: true,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Skye",
    class: "Initiator",
    smoke: false,
    flash: true,
    heal: true,
    molly: false,
    stun: true,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Yoru",
    class: "Duelist",
    smoke: false,
    flash: true,
    heal: false,
    molly: false,
    stun: false,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Astra",
    class: "Controller",
    smoke: true,
    flash: false,
    heal: false,
    molly: false,
    stun: true,
    imageUrl: "",
    altText: "",
  },
  {
    name: "KAY/O",
    class: "Initiator",
    smoke: false,
    flash: true,
    heal: false,
    molly: true,
    stun: false,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Chamber",
    class: "Sentinel",
    smoke: false,
    flash: false,
    heal: false,
    molly: false,
    stun: false,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Neon",
    class: "Duelist",
    smoke: false,
    flash: false,
    heal: false,
    molly: false,
    stun: true,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Fade",
    class: "Initiator",
    smoke: false,
    flash: false,
    heal: false,
    molly: false,
    stun: false,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Harbor",
    class: "Controller",
    smoke: true,
    flash: false,
    heal: false,
    molly: false,
    stun: true,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Gekko",
    class: "Initiator",
    smoke: false,
    flash: true,
    heal: false,
    molly: true,
    stun: true,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Deadlock",
    class: "Sentinel",
    smoke: false,
    flash: false,
    heal: false,
    molly: false,
    stun: true,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Clove",
    class: "Controller",
    smoke: true,
    flash: false,
    heal: true,
    molly: false,
    stun: false,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Vyse",
    class: "Sentinel",
    smoke: false,
    flash: true,
    heal: false,
    molly: true,
    imageUrl: "",
    altText: "",
  },
  {
    name: "Iso",
    class: "Duelist",
    smoke: false,
    flash: false,
    heal: false,
    molly: false,
    imageUrl: "",
    altText: "",
  },
];

export { valorantAgents };
